# Generated by Django 2.2.3 on 2020-01-08 02:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=255, null=True, verbose_name='주소'),
        ),
        migrations.AddField(
            model_name='user',
            name='depart',
            field=models.CharField(max_length=64, null=True, verbose_name='부서'),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(max_length=32, null=True, verbose_name='휴대폰번호'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=32, null=True, verbose_name='전화번호'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(max_length=32, null=True, verbose_name='직급'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=64, null=True, verbose_name='사용자이름'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='생년월일'),
        ),
    ]
